version: '3.7'

services:
  wordpress:
    image: wordpress.slim
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
     - WORDPRESS_DB_USER=root
    ports:
     - 80:80
  mariadb:
    image: mariadb:latest
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
