version: '3.7'

services:
  frontend:
    build:
      context: client/
      target: release
    depends_on:
      - frontend-sidecar-env-gen
    ports:
    - 8081:8080
    env_file:
    - .env
    image: abdennour/go-to-do-frontend:rc
  # in k8s, it will be easier using sidecar with emptyDir vol
  frontend-sidecar-env-gen:
    image: abdennour/dotenv-to-js-object:4ea
    working_dir: /data
    depends on: 
      - db
    healthcheck:
      # healthy when env.js file is not empty
      test: ["CMD", "test", "-s", "/data/env.js"]
      timeout: 1s
      start_period: 1s
      interval: 10s
      retries: 3
    env_file:
    - .env
    command: ->
      --env-vars-filter=REACT_APP_
      --run-as=daemon
      --refresh-period=50
  api:
    build:
      context: server/
      target: release
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DB_CONNECTION: mongodb://appuser:apppass@db:27017/test
      DB_NAME: test
    image: abdennour/go-to-do-api:rc
  db:
    image: bitnami/mongodb:4.4.1
      #- db-data:/abdennour/go-to-do-db:minified
      #- db-data:/bitnami/mongodb.slim
    #depends_on:
      #- frontend
      #- frontend-sidecar-env-gen
    environment:
      MONGODB_ROOT_PASSWORD: adminpass
      MONGODB_DATABASE: test
      MONGODB_USERNAME: appuser
      MONGODB_PASSWORD: apppass
