version: '3'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
    ports:
    - 27017:27017
    volumes:
    - ./data/db:/data/db

  app: 
    container_name: app
    depends_on:
    - mongo
    build: ./app/.
    ports:
    - "5001:5001"
    environment: 
        TRUNK_COMBO: "12345"
    
volumes:
    mongo_vol:
    
    
