version: '3.8'

services:
    backend: 
        build: backend/.
        container_name: photo_backend
        #image: slimpsv/pyphotoapp:latest
        ports:
        - "5000:5000"
        volumes:
        - '~/Documents/Projects/slim-cotw/containers101-networking-3-database/srv/photo/images:/app/static/images' # should map to S3 bucket or similar
        - '~/Documents/Projects/slim-cotw/containers101-networking-3-database/srv/photo/data:/app/data' # will remove when DB service available

    frontend:
        build: frontend/.
        container_name: photo_frontend
        #image: slimpsv/nuxt-fe:latest
        ports: 
        - "3000:3000"
        links: 
        - backend
    
    database: 
        container_name: pgdb 
        image: postgres:latest
        restart: always
        ports: 
        - 5432:5432
        volumes: 
        - ~/Documents/Projects/slim-cotw/containers101-networking-3-database/srv/photo/data/db:/data/db # update to where PG wants data volume
        - ~/Documents/Projects/slim-cotw/containers101-networking-3-database/srv/photo/data/postgres:/var/lib/postgresql/data #update to where PG wants conf file
        environment: 
            POSTGRES_DB: test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            PGDATA: /var/lib/postgresql/data

    # load_balancer: 
    #     build: nginx 
    #     networks:
    #     - photoapp


    